### ISSUE TITLE
A typo in `show.pynb`

### ISSUE THREAD

**Issue by zhihuat** [haowang-cqu/EvilEdit#1]
Just a reminder, there might be a typo in `show.pynb`: 
`make_image_grid([clean_image, bad_pipe], rows=1, cols=2)`. 
Should `bad_pipe` be `bad_image`?

**Comment by haowang02** [comment]
Thanks for the reminder! I've fixed it. You can check the changes in commit f637cc324dfb21dc74b33de9a5ddb12e3e549b1b.
